demo:
  target: demo1
  outputs:
    demo1:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: LAPTOP-81HDQ7QP
      database: master
      schema: amazon_sales
      windows_login: True
      trust_cert: True
    
   